quarkus.http.port=8080
quarkus.application.name=quarkus-app

%dev.quarkus.log.level=DEBUG
%prod.quarkus.log.level=INFO

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${POSTGRES_USER}
quarkus.datasource.password=${POSTGRES_PASSWORD}
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:${POSTGRES_PORT}/shop

%dev.quarkus.hibernate-orm.database.generation=drop-and-create
%dev.quarkus.hibernate-orm.log.sql=true 